# Generated by Django 6.1.1 on 2026-09-04 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('telefone', models.CharField(blank=True, max_length=255, null=True)),
                ('pontos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id_cupom', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipo_desconto', models.CharField(max_length=50)),
                ('valor_minimo', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('data_inicio', models.DateTimeField()),
                ('data_expiracao', models.DateTimeField()),
                ('quantidade_disponivel', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=30)),
                ('admin', models.ForeignKey(db_column='fk_admin_id_admin', on_delete=django.db.models.deletion.CASCADE, to='store.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=30)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('frete', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=8)),
                ('admin', models.ForeignKey(db_column='fk_admin_id_admin', on_delete=django.db.models.deletion.CASCADE, to='store.admin')),
                ('cliente', models.ForeignKey(db_column='fk_cliente_id_clinte', on_delete=django.db.models.deletion.CASCADE, to='store.cliente')),
                ('cupom', models.ForeignKey(blank=True, db_column='fk_cupom_id_cupom', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.cupom')),
            ],
        ),
        migrations.CreateModel(
            name='Possui',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_pedido', models.ForeignKey(db_column='fk_item_pedido_id_item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.itempedido')),
                ('pedido', models.ForeignKey(db_column='fk_pedido_id_pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('admin', models.ForeignKey(db_column='fk_admin_id_admin', on_delete=django.db.models.deletion.CASCADE, to='store.admin')),
            ],
        ),
        migrations.CreateModel(
            name='VariacaoProduto',
            fields=[
                ('id_variacao', models.AutoField(primary_key=True, serialize=False)),
                ('tamanho', models.CharField(max_length=10)),
                ('produto', models.ForeignKey(db_column='fk_produto_id_produto', on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='store.produto')),
            ],
        ),
        migrations.AddField(
            model_name='itempedido',
            name='variacao_produto',
            field=models.ForeignKey(db_column='fk_variacao_produto_id__variacao', on_delete=django.db.models.deletion.CASCADE, to='store.variacaoproduto'),
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id_estoque', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('motivo', models.CharField(max_length=50)),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(db_column='fk_admin_id_admin', on_delete=django.db.models.deletion.CASCADE, to='store.admin')),
                ('pedido', models.ForeignKey(blank=True, db_column='fk_pedido_id_pedido', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.pedido')),
                ('variacao_produto', models.ForeignKey(db_column='fk_variacao_produto_id__variacao', on_delete=django.db.models.deletion.CASCADE, to='store.variacaoproduto')),
            ],
        ),
        migrations.CreateModel(
            name='ReciboPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recibo_id', models.IntegerField()),
                ('id_pagamento', models.IntegerField()),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('metodo', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('data_pagamento', models.DateTimeField()),
                ('cliente', models.ForeignKey(db_column='fk_cliente_id_clinte', on_delete=django.db.models.deletion.CASCADE, to='store.cliente')),
            ],
            options={
                'unique_together': {('recibo_id', 'id_pagamento')},
            },
        ),
    ]
