# Generated by Django 6.1.1 on 2026-09-04 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='admin',
            field=models.ForeignKey(db_column='fk_admin_id', on_delete=django.db.models.deletion.CASCADE, to='store.admin'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='admin',
            field=models.ForeignKey(db_column='fk_admin_id', on_delete=django.db.models.deletion.CASCADE, to='store.admin'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='pedido',
            field=models.ForeignKey(blank=True, db_column='fk_pedido_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.pedido'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='variacao_produto',
            field=models.ForeignKey(db_column='fk_variacao_produto_id', on_delete=django.db.models.deletion.CASCADE, to='store.variacaoproduto'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='variacao_produto',
            field=models.ForeignKey(db_column='fk_variacao_produto_id', on_delete=django.db.models.deletion.CASCADE, to='store.variacaoproduto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='admin',
            field=models.ForeignKey(db_column='fk_admin_id', on_delete=django.db.models.deletion.CASCADE, to='store.admin'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(db_column='fk_cliente_id', on_delete=django.db.models.deletion.CASCADE, to='store.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cupom',
            field=models.ForeignKey(blank=True, db_column='fk_cupom_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.cupom'),
        ),
        migrations.AlterField(
            model_name='possui',
            name='item_pedido',
            field=models.ForeignKey(db_column='fk_item_pedido_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.itempedido'),
        ),
        migrations.AlterField(
            model_name='possui',
            name='pedido',
            field=models.ForeignKey(db_column='fk_pedido_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.pedido'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='admin',
            field=models.ForeignKey(db_column='fk_admin_id', on_delete=django.db.models.deletion.CASCADE, to='store.admin'),
        ),
        migrations.AlterField(
            model_name='recibopagamento',
            name='cliente',
            field=models.ForeignKey(db_column='fk_cliente_id', on_delete=django.db.models.deletion.CASCADE, to='store.cliente'),
        ),
        migrations.AlterField(
            model_name='variacaoproduto',
            name='produto',
            field=models.ForeignKey(db_column='fk_produto_id', on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='store.produto'),
        ),
    ]
