# Generated by Django 6.1.1 on 2026-09-08 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_produto_imagem_alter_cupom_admin_alter_estoque_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='admin',
            field=models.ForeignKey(blank=True, db_column='fk_admin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.admin'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='motivo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='tipo',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Saida', 'Saída')], default='Entrada', max_length=10),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='variacao_produto',
            field=models.ForeignKey(db_column='fk_variacao_produto_id', on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='store.variacaoproduto'),
        ),
    ]
