# Generated by Django 6.1.1 on 2026-09-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_estoque_admin_alter_estoque_motivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacaoproduto',
            name='cor',
            field=models.CharField(blank=True, help_text='Uso interno/controle de estoque', max_length=30, null=True),
        ),
    ]
