# Generated by Django 6.1.1 on 2026-09-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variacaoproduto_cor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variacaoproduto',
            name='cor',
        ),
        migrations.AddField(
            model_name='produto',
            name='cor',
            field=models.CharField(blank=True, help_text='Ex: Branco, Preto ou etc', max_length=30, null=True),
        ),
    ]
