# Generated by Django 6.1.1 on 2026-09-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_cliente_email_remove_cliente_senha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
