# Generated by Django 6.1.1 on 2026-10-01 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_colecao_produto_colecao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colecao',
            options={'verbose_name': 'Coleção', 'verbose_name_plural': 'Coleções'},
        ),
        migrations.AlterModelOptions(
            name='cupom',
            options={'verbose_name': 'Cupom', 'verbose_name_plural': 'Cupons'},
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(db_column='fk_pedido_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='store.pedido'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Possui',
        ),
    ]
