# Generated by Django 6.1.1 on 2026-10-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_colecao_options_alter_cupom_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='id_transacao_gateway',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='qr_code_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='qr_code_pix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ticket_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
