# Generated by Django 6.1.1 on 2026-10-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_pedido_id_transacao_gateway_pedido_metodo_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=30),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='tipo_desconto',
            field=models.CharField(choices=[('fixo', 'Valor Fixo (R$)'), ('porcentagem', 'Porcentagem (%)')], default='fixo', max_length=20),
        ),
    ]
