# Generated by Django 6.1.1 on 2026-10-10 15:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_cupom_status_alter_cupom_tipo_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Altura da embalagem individual em cm.', max_digits=5),
        ),
        migrations.AddField(
            model_name='produto',
            name='comprimento',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Comprimento da embalagem individual em cm.', max_digits=5),
        ),
        migrations.AddField(
            model_name='produto',
            name='largura',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Largura da embalagem individual em cm.', max_digits=5),
        ),
        migrations.AddField(
            model_name='produto',
            name='peso',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.350'), help_text='Peso em quilogramas (kg). Ex: 0.350 para 350g.', max_digits=5, max_length=5),
        ),
    ]
