# Generated by Django 6.1.1 on 2026-10-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_produto_altura_produto_comprimento_produto_largura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='comprimento',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='largura',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='peso',
        ),
    ]
