# Generated by Django 6.1.1 on 2026-10-10 15:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_produto_altura_remove_produto_comprimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Altura em cm', max_digits=5),
        ),
        migrations.AddField(
            model_name='produto',
            name='comprimento',
            field=models.DecimalField(decimal_places=2, default=Decimal('35.00'), help_text='Comprimento em cm', max_digits=5),
        ),
        migrations.AddField(
            model_name='produto',
            name='largura',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Largura em cm', max_digits=5),
        ),
        migrations.AddField(
            model_name='produto',
            name='peso',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.350'), help_text='Peso em kg (ex: 0.350 para 350g)', max_digits=5),
        ),
    ]
