# Generated by Django 6.1.1 on 2026-10-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_produto_altura_produto_comprimento_produto_largura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='bairro_entrega',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cep_entrega',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cidade_entrega',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='complemento_entrega',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco_entrega',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_entrega',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_entrega',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='prazo_frete_dias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='servico_frete_id',
            field=models.IntegerField(blank=True, help_text='ID da transportadora/serviço no Melhor Envio', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='servico_frete_nome',
            field=models.CharField(blank=True, help_text='Ex: PAC, SEDEX', max_length=50, null=True),
        ),
    ]
